<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <NoWarn>1701;1702;IDE0063;IDE0290</NoWarn>
    <AssemblyTitle>Amazon Seller Central Image Packager</AssemblyTitle>
    <AssemblyName>AmazonSellerCentralImagePackager</AssemblyName>
    <ApplicationIcon>Resources\logo.ico</ApplicationIcon>
    <Version>2.0.0</Version>
    <Authors>Dante Karl Wackermann</Authors>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\banner-ui.png" />
    <None Remove="Resources\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Resources\banner-ui.png" />
    <AvaloniaResource Include="Resources\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.11" />
    <PackageReference Include="neXn.Analyzers" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="neXn.Lib" Version="10.0.7" />
    <PackageReference Include="neXn.Lib.ConfigurationHandler" Version="10.1.2" />
    <PackageReference Include="neXn.Ui.Avalonia" Version="10.2.4" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Processor\Processor.csproj" />
  </ItemGroup>
  
</Project>
