; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Amazon Picture Packager"
#define MyAppVersion "1.2"
#define MyAppPublisher "neXn-Systems"
#define MyAppURL "https://github.com/spreedated/AmazonPicturePackager"
#define MyAppExeName "AmazonPicturePackager.exe"

[Setup]
AppId={{1206B66A-7C5D-4A40-914B-E17FEDEEB96A}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=Z:\DesignblecheAmazonPicturePackager\LICENSE.txt
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputBaseFilename={#MyAppName}_Setup_{#MyAppVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
DisableWelcomePage=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "AmazonPicturePackager\bin\Release\net9.0\publish\win-x64\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "AmazonPicturePackager\bin\Release\net9.0\publish\win-x64\AmazonPicturePackager.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "AmazonPicturePackager\bin\Release\net9.0\publish\win-x64\av_libglesv2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "AmazonPicturePackager\bin\Release\net9.0\publish\win-x64\libHarfBuzzSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "AmazonPicturePackager\bin\Release\net9.0\publish\win-x64\libSkiaSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "AmazonPicturePackager\bin\Release\net9.0\publish\win-x64\neXn.Lib.ConfigurationHandler.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "AmazonPicturePackager\bin\Release\net9.0\publish\win-x64\neXn.Ui.Avalonia.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "AmazonPicturePackager\bin\Release\net9.0\publish\win-x64\neXn.Ui.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "AmazonPicturePackager\bin\Release\net9.0\publish\win-x64\Processor.pdb"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

